options:
  machineType: N1_HIGHCPU_8
  env:
  - 'DOCKER_API_VERSION=1.41'

# Substitutions
# _ORG_NAME - the artifact registry repository name, e.g. 'myOrg'
# _ROLLBAR_MAP_KEY - the Rollbar source map access token for this project, if set
# _IMAGE_NAME - the name of the image to build, e.g. 'mcp'
# _STAGE_PROJECT - the GCP project to deploy staging builds to, e.g. 'stage'
# _STAGE_REGION - the GCP region to deploy staging builds to, e.g. 'us-west1'
# _STAGE_CLUSTER - the GKE cluster to deploy staging builds to, e.g. 'stage-mcp'
# _RELEASE_PROJECT - the GCP project to deploy release builds to, e.g. 'release'
# _RELEASE_REGION - the GCP region to deploy release builds to, e.g. 'us-west1'
# _RELEASE_CLUSTER - the GKE cluster to deploy release builds to, e.g. 'release-mcp'
# _LOGS_BUCKET - the GCS bucket to write build logs to, e.g. 'gs://my-build-logs'

steps:

# Build Images

- id: mcpBuild
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:tempImage'
  - '--file=./Dockerfile'
  - '.'

- id: mcpPush
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -euo pipefail
    IFS=$'\n\t'

    if [[ -n '$TAG_NAME' ]]; then
      docker tag us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:tempImage us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:$TAG_NAME
      docker push us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:$BRANCH_NAME
    else
      docker tag us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:tempImage us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:$BRANCH_NAME
      docker push us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:$BRANCH_NAME
    fi

    docker rmi us-docker.pkg.dev/$PROJECT_ID/$_ORG_NAME/$_IMAGE_NAME:tempImage
  waitFor: ['mcpBuild' ]

# Redeploy staging or release if this is a develop or release branch build
- id: redeploy
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -euo pipefail
    IFS=$'\n\t'

    if [[ '$BRANCH_NAME' == 'develop' ]]; then
      gcloud container clusters get-credentials --project='$_STAGE_PROJECT' --region='$_STAGE_REGION' $_STAGE_CLUSTER
      kubectl rollout restart deployment/$_STAGE_CLUSTER-mcp
    fi

    if [[ '$BRANCH_NAME' == 'release' ]]; then
      gcloud container clusters get-credentials --project='$_RELEASE_PROJECT' --region='$_RELEASE_REGION' $_RELEASE_CLUSTER
      kubectl rollout restart deployment/$_RELEASE_CLUSTER-mcp
    fi
  waitFor: ['mcpPush']

timeout: 600s
logsBucket: '$_LOGS_BUCKET'
