name: Update Platform VEX

on:
  issues:
    types: [closed]

concurrency:
  group: issue-vex-assertions
  cancel-in-progress: false

jobs:
  update-vex:
    if: contains(github.event.issue.labels.*.name, 'vex-pending')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout
        # tag v4.0.0
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # v3.2.0
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: 4830546
          private-key: ${{ secrets.VEX_APP_PRIVATE_KEY }}
          repositories: "losant-vexhub"

      # v3
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}
      # v3
      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db

      - uses: Losant/losant-vex-tools/issue-vex-assertions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VEX_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          vex_repo: Losant/losant-vexhub
          gcp_project: losant-core
          cloud_run_job: gca-vex-generator-mcp
          cloud_run_region: us-central1
